# Generated by Django 2.2.5 on 2020-01-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('summary', models.CharField(max_length=1024)),
                ('storyline', models.CharField(max_length=1024, null=True)),
                ('ordered_keywords', models.CharField(max_length=2056, null=True)),
                ('cover', models.URLField(null=True)),
                ('genres', models.ManyToManyField(db_table='game_genre', related_name='games', to='gameplan.Genre')),
            ],
        ),
    ]
