# Generated by Django 2.2.5 on 2020-01-19 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('cover_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('franchise_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GameEngine',
            fields=[
                ('game_engine_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('game_mode_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPerspective',
            fields=[
                ('player_perspective_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('screenshot_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('video_id', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('website_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseDate',
            fields=[
                ('release_date_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('date', models.CharField(max_length=12, null=True)),
                ('human', models.CharField(max_length=12, null=True)),
                ('region', models.IntegerField(null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplan.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='InvolvedCompany',
            fields=[
                ('involved_company_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('developer', models.BooleanField()),
                ('publisher', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplan.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('summary', models.CharField(max_length=1024)),
                ('storyline', models.CharField(max_length=1024, null=True)),
                ('ordered_keywords', models.CharField(max_length=2056, null=True)),
                ('cover', models.URLField(null=True)),
                ('category', models.CharField(max_length=3, null=True)),
                ('first_release_date', models.CharField(max_length=12, null=True)),
                ('hypes', models.IntegerField(null=True)),
                ('keywords', models.CharField(max_length=5000, null=True)),
                ('popularity', models.FloatField(null=True)),
                ('total_rating', models.FloatField(null=True)),
                ('total_rating_count', models.IntegerField(null=True)),
                ('url', models.URLField(null=True)),
                ('franchise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameplan.Franchise')),
                ('game_engines', models.ManyToManyField(db_table='game_game_engine', to='gameplan.GameEngine')),
                ('game_modes', models.ManyToManyField(db_table='game_game_mode', to='gameplan.GameMode')),
                ('genres', models.ManyToManyField(db_table='game_genre', to='gameplan.Genre')),
                ('involved_companies', models.ManyToManyField(db_table='game_involved_company', to='gameplan.InvolvedCompany')),
                ('platforms', models.ManyToManyField(db_table='game_platform', to='gameplan.Platform')),
                ('player_perspectives', models.ManyToManyField(db_table='game_player_perspectives', to='gameplan.PlayerPerspective')),
                ('release_dates', models.ManyToManyField(db_table='game_release_dates', to='gameplan.ReleaseDate')),
                ('screenshots', models.ManyToManyField(db_table='game_screenshots', to='gameplan.Screenshot')),
                ('themes', models.ManyToManyField(db_table='game_theme', to='gameplan.Theme')),
                ('videos', models.ManyToManyField(db_table='game_video', to='gameplan.Video')),
                ('websites', models.ManyToManyField(db_table='game_website', to='gameplan.Website')),
            ],
        ),
    ]
