# Generated by Django 3.0.3 on 2020-02-27 10:21

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('gameplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('title'), nulls_last=True)]},
        ),
    ]
