# Generated by Django 2.2.5 on 2020-01-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releasedate',
            old_name='release_data_id',
            new_name='release_date_id',
        ),
        migrations.AlterField(
            model_name='game',
            name='first_release_date',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='franchise',
            field=models.ForeignKey(null=True, on_delete=None, to='gameplan.Franchise'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_engines',
            field=models.ManyToManyField(db_table='game_game_engine', null=True, to='gameplan.GameEngine'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_modes',
            field=models.ManyToManyField(db_table='game_game_mode', null=True, to='gameplan.GameMode'),
        ),
        migrations.AlterField(
            model_name='game',
            name='hypes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='involved_companies',
            field=models.ManyToManyField(db_table='game_involved_company', null=True, to='gameplan.InvolvedCompany'),
        ),
        migrations.AlterField(
            model_name='game',
            name='keywords',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(db_table='game_platform', null=True, to='gameplan.Platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_perspectives',
            field=models.ManyToManyField(db_table='game_player_perspectives', null=True, to='gameplan.PlayerPerspective'),
        ),
        migrations.AlterField(
            model_name='game',
            name='popularity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_dates',
            field=models.ManyToManyField(db_table='game_release_dates', null=True, to='gameplan.ReleaseDate'),
        ),
        migrations.AlterField(
            model_name='game',
            name='screenshots',
            field=models.ManyToManyField(db_table='game_screenshots', null=True, to='gameplan.Screenshot'),
        ),
        migrations.AlterField(
            model_name='game',
            name='themes',
            field=models.ManyToManyField(db_table='game_theme', null=True, to='gameplan.Theme'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_to_beat',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='total_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='total_rating_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='videos',
            field=models.ManyToManyField(db_table='game_video', null=True, to='gameplan.Video'),
        ),
        migrations.AlterField(
            model_name='game',
            name='websites',
            field=models.ManyToManyField(db_table='game_website', null=True, to='gameplan.Website'),
        ),
    ]
