# Generated by Django 2.2.5 on 2020-01-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='storyline',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
