# Generated by Django 2.2.5 on 2020-01-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplan', '0002_auto_20200109_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasedate',
            name='date',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='releasedate',
            name='human',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
