# Generated by Django 2.2.5 on 2020-03-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplan', '0002_auto_20200227_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerperspective',
            old_name='player_perspective_id',
            new_name='playerperspective_id',
        ),
    ]
