# Generated by Django 2.2.5 on 2020-01-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplan', '0004_remove_game_time_to_beat'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedate',
            name='region',
            field=models.IntegerField(null=True),
        ),
    ]
