# Generated by Django 2.2.5 on 2020-01-09 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplan', '0005_releasedate_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='franchise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameplan.Franchise'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_engines',
            field=models.ManyToManyField(db_table='game_game_engine', to='gameplan.GameEngine'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_modes',
            field=models.ManyToManyField(db_table='game_game_mode', to='gameplan.GameMode'),
        ),
        migrations.AlterField(
            model_name='game',
            name='involved_companies',
            field=models.ManyToManyField(db_table='game_involved_company', to='gameplan.InvolvedCompany'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(db_table='game_platform', to='gameplan.Platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_perspectives',
            field=models.ManyToManyField(db_table='game_player_perspectives', to='gameplan.PlayerPerspective'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_dates',
            field=models.ManyToManyField(db_table='game_release_dates', to='gameplan.ReleaseDate'),
        ),
        migrations.AlterField(
            model_name='game',
            name='screenshots',
            field=models.ManyToManyField(db_table='game_screenshots', to='gameplan.Screenshot'),
        ),
        migrations.AlterField(
            model_name='game',
            name='themes',
            field=models.ManyToManyField(db_table='game_theme', to='gameplan.Theme'),
        ),
        migrations.AlterField(
            model_name='game',
            name='videos',
            field=models.ManyToManyField(db_table='game_video', to='gameplan.Video'),
        ),
        migrations.AlterField(
            model_name='game',
            name='websites',
            field=models.ManyToManyField(db_table='game_website', to='gameplan.Website'),
        ),
        migrations.AlterField(
            model_name='involvedcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplan.Company'),
        ),
        migrations.AlterField(
            model_name='releasedate',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplan.Platform'),
        ),
    ]
