# Generated by Django 2.2.5 on 2020-01-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplan', '0006_auto_20200109_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
