# Generated by Django 2.2.5 on 2020-01-22 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationPairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('support', models.FloatField()),
                ('confidence', models.FloatField()),
                ('from_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_game', to='gameplan.Game')),
                ('to_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_game', to='gameplan.Game')),
            ],
        ),
    ]
