# Generated by Django 2.2.5 on 2020-03-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationpairing',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
