# Generated by Django 2.2.5 on 2020-03-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20200301_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationpairing',
            name='confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recommendationpairing',
            name='support',
            field=models.FloatField(null=True),
        ),
    ]
