# Generated by Django 2.2.5 on 2020-01-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='session_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
