# Generated by Django 2.2.5 on 2020-01-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='create',
            new_name='created',
        ),
    ]
