# Generated by Django 2.2.5 on 2020-01-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0002_auto_20200114_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user_id',
            new_name='user',
        ),
    ]
